### ISSUE TITLE
Roll Stat & Generate Hex Macros

### ISSUE THREAD

**Issue by Tor2gaVerde** [Futil/foundry-mausritter#10]
Will there be documentation with these two macros? They don't appear to work in my setup.

-Thank you

**Comment by brunocalado** [comment]
hex fix
[Mausritter-Hex - Copia.txt](https://github.com/Futil/foundry-mausritter/files/7150495/Mausritter-Hex.-.Copia.txt)

**Comment by brunocalado** [comment]
Hex fix: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Sistemas%20Diversos/Mausritter-Hex.js

**Comment by brunocalado** [comment]
fix npc: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Sistemas%20Diversos/Mausritter-InstantNPC.js
