### ISSUE TITLE
Roll Stat Macro don't work 

### ISSUE THREAD

**Issue by brunocalado** [Futil/foundry-mausritter#16]
![image](https://user-images.githubusercontent.com/4999783/133006968-df14724b-0e72-45f6-8781-7248efb02be8.png)

**Comment by thorgibrewer** [comment]
Hi @brunocalado ,

This macro works if you have yourself assigned to a User via the User Configuration. I.E. all players should be able to default it per their character sheet. But as a GM I had to set myself as as a specific player. I'm not sure what work would need to be done for it to be agnostic if a "User Configuration" selected character as opposed to say a token select.

**Comment by brunocalado** [comment]
tks
