### ISSUE TITLE
The game system doesn't work at all in V10

### ISSUE THREAD

**Issue by struckyCZ** [Futil/foundry-mausritter#27]
Cannot be installed. If it was installed prior to the V10 update, it just disappears, but Foundry still announces an error.
![image](https://user-images.githubusercontent.com/80347865/188428926-aae49bd8-9e94-4b24-9c1e-04988c7a8a23.png)

**Comment by Futil** [comment]
I am working on the upgrade to v10, but it will likely be at least a week. I recommend staying in V9 for the time being if you want to use the module

**Comment by Mathias2803** [comment]
Is there a plan when it's possible to get the system with V10 running?

**Comment by Mathias2803** [comment]
Any updates about the status?

**Comment by Futil** [comment]
Pushed an update out now! I'm terribly sorry about the delay, it's been hard to find time to do this.
