### ISSUE TITLE
Overlay div on items in Player inventory blocking actions

### ISSUE THREAD

**Issue by aniki21** [Futil/foundry-mausritter#29]
Items added to the player sheet can't have their title clicked (for dice rolls) or the usage pips adjusted due to the presence of an "overlay" `div` that seems to be blocking clicks.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/305037/199973111-fc6da0c6-983f-4507-9f62-8888220b7f7d.png">

Removing this `div` using developer tools allows the functionality to be used as normal. This `div` is not present on the card  when it appears on NPC, hireling or storage character sheets.

**Comment by aniki21** [comment]
Adding the CSS `pointer-events: none` to the `.mausritter .overlay` class also allows the items to function normally (though I've only tested this in Chrome).

**Comment by curtishay** [comment]
I ran into this with the standalone version of Foundry v10 as well (which I know just runs a Chrome container).

**Comment by Futil** [comment]
Oops, I thought I pushed that. I'll fix it ASAP

**Comment by Futil** [comment]
It should be fixed in the latest patch.
