### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by brunocalado** [Futil/foundry-mausritter#3]
Hi.

I create the hex tables. Maybe you can add then to the system compendium

Tables
![image](https://user-images.githubusercontent.com/4999783/103014508-9f112080-451d-11eb-9b20-87c69bc1ba4e.png)

Download
[mausritter.zip](https://github.com/Futil/foundry-mausritter/files/5736008/mausritter.zip)

**Comment by brunocalado** [comment]
Journal with weather table.

[fvtt-JournalEntry-Weather.zip](https://github.com/Futil/foundry-mausritter/files/5736064/fvtt-JournalEntry-Weather.zip)

**Comment by Futil** [comment]
Thanks! I'll bring them into the system. I appreciate the work.

**Comment by brunocalado** [comment]
How much from the book can I send to you?

**Comment by Futil** [comment]
I think the rolltables should be fine, same with creatures and items. I can't use any art other than what's already in the system though. I'll check with Isaac for clarification.

**Comment by brunocalado** [comment]
> Journal with weather table.
> 
> [fvtt-JournalEntry-Weather.zip](https://github.com/Futil/foundry-mausritter/files/5736064/fvtt-JournalEntry-Weather.zip)

Will you add weather table?

**Comment by Futil** [comment]
The weather table is empty for me.

**Comment by brunocalado** [comment]
It's a journal.

![image](https://user-images.githubusercontent.com/4999783/103151999-03242680-4762-11eb-9c14-f3671750f280.png)
