### ISSUE TITLE
Items in Storage containers are being shown as storage

### ISSUE THREAD

**Issue by curtishay** [Futil/foundry-mausritter#30]
I really appreciate the update to v10, it's great! That said, I noticed an issue after converting a campaign to the new version. All of the items that are put into storage show as being storage themselves. I tried deleting and recreating the items in storage, but the problem came back after I logged out and back in again. Here's what it looks like:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/48147675/200145868-8268dfc1-16bf-4d07-a37b-86a5dd9e746e.png">

**Comment by Futil** [comment]
I'm looking into it! Thanks for bringing it into my attention
