### ISSUE TITLE
Update 'Mad' condition to 'Drained' per errata

### ISSUE THREAD

**Issue by the-bowmanizer** [Futil/foundry-mausritter#31]
In newer copies of the game, the 'Mad' condition has been changed to 'Drained.' Just a change of terminology, they're mechanically identical.

> Miscasts
> Whenever one or more 6s are rolled when casting a
> spell, the caster takes d6 damage to WIL for each
> 6 rolled. Then make a WIL save. If failed, take the
> Drained Condition.

The author, Isaac Williams, posted the rationale on his Discord server.

> What is the difference between the first and second printings of the rulebook?
> 
> Not much! There's a couple of typo fixes, and the combat example of play has been clarified a little.
> 
> The only major change is renaming the condition that a mouse gains when a spell miscasts. In the first printing, this is "Mad", but has been changed to "Drained" in the second printing (and pdfs version 2.2 and greater). This naming is more inclusive and more appropriately describes the Condition.

**Comment by jandanecki** [comment]
Done in #32
