### ISSUE TITLE
Unable to drag items to Macro bar, or use script as workaround

### ISSUE THREAD

**Issue by jax7778** [Futil/foundry-mausritter#38]
Hello, first, thank you for all your work on this. I know it is done in your spare time. 

I think the basic damage rolls are broken. The instructions say to drag and drop the item from your character sheet to the actions menu, but this doesn’t work. Your instructions also offer a work around to manually paste a script, using the item name, but this also seems to fail.

I tried using the item descriptive name (such as Axe) and I also tried using the item name listed in the owned item config, which is a unique alphanumeric string, which also fails, with the error that my controlled actor does not have an item named “unique string here”

I am getting ready to start a campaign in foundry, but I would like a way for my players to roll damage from the actions menu or character sheets. Is there something I am missing, or another workaround?

Thanks in advance for any help.

**Comment by krasnoludkolo** [comment]
Do you have up to date foundry? I got similar issue and updating foundry solved it

**Comment by jax7778** [comment]
> Do you have up to date foundry? I got similar issue and updating foundry solved it

Yes, I am currently running  10.291. But I might be missing something? Were you able to just drag an weapon from the sheet to the bar? Or did you use the script as a work around? If you are using the script, can you give me an example? I might be formatting something incorrectly.

**Comment by jax7778** [comment]
So, as a heads up to anyone else that stumbles across this. I was being a bit of an idiot. I did not realize you could click the name of the item cards to roll in the sheet. I thought the only way was to add them to the hotbar, and with that not working the sheet was not really functional, since it looks to me like basic damage rolls just didn't work period. 

After you drag something into the sheet, just click the name to roll damage or post the item/condition to chat. Works like a charm. 

I also got the roll macros working with the script (I still can't get drag and drop working, but doesn't matter much now)  Just use the real item name, such as "Axe" not the ID. Not sure why it did not work the first time. 

I am closing this out.
