### ISSUE TITLE
Instant NPC

### ISSUE THREAD

**Issue by brunocalado** [Futil/foundry-mausritter#7]
This macro can roll all tables for NPC and create an actor.

You need to add all tables to a compendium with a label Tables. But, you can change the label.

This is the macro: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Sistemas%20Diversos/Mausritter-InstantNPC.js

This is the db with tables.
[tables.zip](https://github.com/Futil/foundry-mausritter/files/5742567/tables.zip)

![image](https://user-images.githubusercontent.com/4999783/103143959-c32c5780-46ff-11eb-9133-b8a3a94c90a8.png)

**Comment by Futil** [comment]
Thanks! This is wonderful, I'll get this into the official macros.

**Comment by thorgibrewer** [comment]
Curious, on this macro and the others I'm getting a couple warnings and errors. The warning seems like come v0.9 of foundry will break these macros. The errors on the other hand are preventing me from using the macros. I'm not a coder so any insight into these would be greatly appreciated. My console errors are below after running the NPC Generator Macro.
![image](https://user-images.githubusercontent.com/69551564/129986401-97f30e2d-4caf-4c3b-a265-a47050e4cc6e.png)

**Comment by brunocalado** [comment]
I updated the macro. It's working now.

Link: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Sistemas%20Diversos/Mausritter-InstantNPC.js

**Comment by thorgibrewer** [comment]
Thanks! I got this one to work with a friend ... totally just overwrote our work though with what you have so glad this one works too haha. 

By the way the weather and hex generators didn't seem to work either. Do you happen to have a fix too? @brunocalado

**Comment by Bynouz** [comment]
Hello, I see in your "macro" for the atribut "3d6kh2" but in the rules this is just 2d6 : "Typical hirelings will have:
d6 hp, STR 2d6, DEX 2d6, WIL 2d6"

**Comment by Bynouz** [comment]
Hello, I see in your "macro" for the atribut "3d6kh2" but in the rules this is just 2d6 : "Typical hirelings will have:
d6 hp, STR 2d6, DEX 2d6, WIL 2d6"
